pipeline {
    agent any
  
    stages {
        stage('Build') { 
            steps {
                echo 'Building'
                nodejs('npm') {
                    sh 'npm install'
                }
            }
        }
        stage('Test') { 
            steps {
                echo 'Testing'
                nodejs('npm') {
                    sh 'npm run test'
                }
            }
        }
    }

    post {
        failure {
            echo 'Success'
            emailext attachLog: true,
                body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
                recipientProviders: [developers(), requestor()],
                to: 'peepeek18@gmail.com',
                subject: "Build error"
        }
        success {
            echo 'Fail'
            emailext attachLog: true,
                body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
                recipientProviders: [developers(), requestor()],
                to: 'peepeek18@gmail.com',
                subject: "Success build"
        }
    }
}
