version: '3.3'
services: 
    build:
        container_name: nodechat-build
        image: nodechat-build: latest
        build: 
            context: .
            dockerfile: Dockerfile-build
    test: 
        container_name: nodechat-test
        image: nodechat-test:latest
        build: 
            context: .
            dockerfile: Dockerfile-test
        depends_on:
            - build