version: "3.9"
services:
  deltachatbuild:
    image: deltachat-build:latest
    build:
      context: .
      dockerfile: Dockerfile
  deltachattest:
    image: deltachat-test:latest
    build:
      context: .
      dockerfile: ./test/Dockerfile
    depends_on: 
      - deltachatbuild


