pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo 'Building...'
				git url: 'https://github.com/Siluk98/deltachat-desktop.git'
				dir('Docker')
				{
					sh 'pwd'
					sf 'ls -R'
					sh 'docker-compose -f docker-compose.yaml up build-agent'
				}
            }
			post
			{
				failure
				{
					echo 'Build failed'
					emailext attachLog: true,
						body: "Status: ${currentBuild.currentResult}",
						recipientProviders: [[$class: 'DevelopersRecipientProvider']],
						subject: 'Build failed',
						to: 'silukpl@gmail.com'
				}
				success
				{
					echo 'Build completed'
				}
			}
		}
		stage('Test') {
			when {
				expression {
					currentBuild.result == 'SUCCESS'
				}
			}
			steps {
				echo 'Testing...'
				git url: 'https://github.com/Siluk98/deltachat-desktop.git'
				dir('Docker')
				{
					sh 'docker-compose up test-agent'
				}
			}
			post {
				failure {
					echo 'Tests failed'
					emailext attachLog: true,
						body: "Status: ${currentBuild.currentResult}",
						recipientProviders: [[$class: 'DevelopersRecipientProvider']],
						subject: 'Tests failed',
						to: 'silukpl@gmail.com'
				}
				success {
					echo 'Tests completed'
					
				}
			}
		}
		stage('Deploy') {
			when {
				expression {
					currentBuild.result == 'SUCCESS'
				}
			}
			steps {
				echo 'Deploying...'
			}
			post
			{
				failure {
					echo 'Deployment failed'
					emailext attachLog: true,
						body: "Status: ${currentBuild.currentResult}",
						recipientProviders: [[$class: 'DevelopersRecipientProvider']],
						subject: 'Deployment failed',
						to: 'silukpl@gmail.com'
				}
				success {
					echo 'Deployment completed'
				}
			}
		}
    }
	post {
		success {
			echo 'Pipeline completed'
			emailext attachLog: true,
		    		body: "Status: ${currentBuild.currentResult}",
		    		recipientProviders: [[$class: 'DevelopersRecipientProvider']],
		    		subject: 'Pipeline completed',
		    		to: 'silukpl@gmail.com'
		}
		failure {
			echo 'Pipeline failed'
			emailext attachLog: true,
		    		body: "Status: ${currentBuild.currentResult}",
		    		recipientProviders: [[$class: 'DevelopersRecipientProvider']],
		    		subject: 'Pipeline failed',
		    		to: 'silukpl@gmail.com'
		}
	}
}
