apiVersion: apps/v1
kind: Deployment
metadata:
  name: komunikator-deployment
  labels:
    app: komunikator2
spec:
  replicas: 6
  selector:
    matchLabels:
      app: komunikator2
  template:
    metadata:
      labels:
        app: komunikator2
    spec:
      containers:
      - name: komunikator-deployment
        image: kingsaszas/socketio:messenger
        ports:
        - containerPort: 9999
