version: '3.3'
services:
 lab04-build:
  container_name: lab04-app
  image: node-app:latest
  build:
   context: .
   dockerfile: build-agent/Dockerfilebuild
 lab04-test:
  container_name: lab04-test
  image: node-test:latest
  build:
   context: .
   dockerfile: test-agent/Dockerfiletest
  depends_on:
  - lab04-build
