pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                checkout scm
                sh 'curl -sL https://deb.nodesource.com/setup_14.x | bash -'
                sh 'apt-get install nodejs -y'
                sh 'npm install --global --force yarn'
		            echo 'Building....'
		}
	}
	stage('Test') {
    when {
                expression {
                    currentBuild.result == null || currentBuild.result == 'SUCCESS'
                }
     }
		 steps {
			echo 'Testing....'
			sh 'npm run test'
			
		}
        }
        stage('Deploy') {
            steps {
                echo 'Deploying....'
            }
        }
    }
    
    post {
    	
    	success {
	 emailext attachLog: true, 
		 body: "${currentBuild.result}: ${BUILD_URL}", 
		 compressLog: true, 
		 subject: "Build Notification: ${JOB_NAME}-Build# ${BUILD_NUMBER} ${currentBuild.result}", 
		 to: 'laskawska.kinga@gmail.com'
		
    	}
    	
    	failure {
		emailext attachLog: true,
			body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}", 
			subject: ' Jenkins notification', 
			to: 'laskawska.kinga@gmail.com'
    	}
    }
}
