pipeline {

agent docker {

}

stages {
	 stage('Build') {
	  steps {
	   echo 'Building.'
	   	sh 'npm --version'
	   	sh 'git clone https://github.com/KamilaNowak/messaging-app-for-docker
	   	sh 'docker-compose up -d'
	   	
	   }
	}
	 stage('Test') {
	  steps {
	   	echo 'Testing.'
	   	sh '../Docker/test.sh'
	   }
	}
    }
}
