pipeline{
    agent any
    tools {nodesj "NodeJS"}
    stages {
        stage('Build') {
            steps{
                echo 'Building'
                sh 'git pull origin master'
                checkout scm
                sh 'npm install'
                sh 'npm run build'    
            }
            post{
            failure {
                emailext attachLog: true,
                    body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ",
                    recipientProviders: [developers(), requestor()],
                    to: 'kocurekmagdalena7@gmail.com',
                    subject: "Failure Jenkins Build${currentBuild.currentResult} : Job ${env.JOB_NAME}"
            }
            success {
            emailext attachLog: true,
                body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ",
                recipientProviders: [developers(), requestor()],
                to: 'kocurekmagdalena7@gmail.com',
                subject: "Success Jenkins Build ${currentBuild.currentResult} : Job ${env.JOB_NAME}"
                 }
         }
        }
        
        stage('Test'){
          when {
            expression {currentBuild.result == 'SUCCESS' }
           }

          steps{
            echo 'Testing'
            sh 'npm run test'
            }   
            
            
           post{
              success{
            emailext attachLog: true,
            
            body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ",
            recipientProviders: [developers(), requestor()],
            subject: "Success Jenkins Test ${currentBuild.currentResult}: Job ${env.JOB_NAME}",
             to: 'kocurekmagdalena7@gmail.com'        
               }
          failure{
            emailext attachLog: true,
            body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ",
            recipientProviders: [developers(), requestor()],
            subject: "Failure Jenkins Test ${currentBuild.currentResult}: Job ${env.JOB_NAME}",
             to: 'kocurekmagdalena7@gmail.com'        
             }   
          }      
        }
    }
}
