pipeline {
    agent any

    tools { nodejs "node"}

    stages {
        stage('Test') {
            steps {
                echo 'Testing..'
                sh 'npm install'
                sh 'npm test'
            }
        }
    }
    post {
        success{
            emailext(
                attachLog: true,
                body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
                recipientProviders: [developers(), requestor()],
                subject: "Success Jenkins Build ${currentBuild.currentResult}: Job ${env.JOB_NAME}",
                to: 'pduda.98@gmail.com'
            )
        }
        failure{
            emailext(
                attachLog: true,
                body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
                recipientProviders: [developers(), requestor()],
                subject: "Failure Jenkins Build ${currentBuild.currentResult}: Job ${env.JOB_NAME}",
                to: 'pduda.98@gmail.com'
            )
        }
    }
}