pipeline {
    agent any

    tools { nodejs "node"}

    stages {
        stage('Build') {
            steps {
                echo 'Building..'
                sh 'git pull origin master'
                sh 'npm install'
            }
            post {
                success{
                    emailext(
                        attachLog: true,
                        body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
                        recipientProviders: [developers(), requestor()],
                        subject: "Build succeeded ${currentBuild.currentResult}: Job ${env.JOB_NAME}",
                        to: 'pduda.98@gmail.com'
                    )
                }
                failure{
                    emailext(
                        attachLog: true,
                        body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
                        recipientProviders: [developers(), requestor()],
                        subject: "Build failed ${currentBuild.currentResult}: Job ${env.JOB_NAME}",
                        to: 'pduda.98@gmail.com'
                    )
                }
            }
        }
        stage('Test') {
            steps {
                echo 'Testing..'
                sh 'npm install'
                sh 'npm test'
            }
            post {
                success{
                    emailext(
                        attachLog: true,
                        body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
                        recipientProviders: [developers(), requestor()],
                        subject: "Tests succeeded ${currentBuild.currentResult}: Job ${env.JOB_NAME}",
                        to: 'pduda.98@gmail.com'
                    )
                }
                failure{
                    emailext(
                        attachLog: true,
                        body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
                        recipientProviders: [developers(), requestor()],
                        subject: "Tests failed ${currentBuild.currentResult}: Job ${env.JOB_NAME}",
                        to: 'pduda.98@gmail.com'
                    )
                }
            }
        }
        stage('Deploy') {
            steps {
                echo 'Deploying..'
                sh 'docker build -t node_chat_deploy -f Dockerfile_deploy .'
                sh 'docker run -d node_chat_deploy'
            }
            post {
                success{
                    emailext(
                        attachLog: true,
                        body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
                        recipientProviders: [developers(), requestor()],
                        subject: "Deploy succeeded ${currentBuild.currentResult}: Job ${env.JOB_NAME}",
                        to: 'pduda.98@gmail.com'
                    )
                }
                failure{
                    emailext(
                        attachLog: true,
                        body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
                        recipientProviders: [developers(), requestor()],
                        subject: "Deploy failed ${currentBuild.currentResult}: Job ${env.JOB_NAME}",
                        to: 'pduda.98@gmail.com'
                    )
                }
            }
        }
    }
}