apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-chat-app-deployment
  labels:
    app: node-chat-app
spec:
  replicas: 6
  selector:
    matchLabels:
      app: node-chat-app
  template:
    metadata:
      labels:
        app: node-chat-app
    spec:
      containers:
      - name: node-chat-app
        image: mkocurek7/myjenkins-blueocean:1.1
        ports:
        - containerPort: 80

