apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-chat-app-deployment
  labels:
    app: node-chat-app
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node-chat-app
  template:
    metadata:
      labels:
        app: node-chat-app
    spec:
      containers:
      - name: jenkins-blueocean
        image: myjenkins-blueocean:1.1
        ports:
        - containerPort: 80

