version: '3.8'
services:
 build-agent:
  container_name: build-agent-deltachat
  image: build:latest
  build:
   context: .
   dockerfile: Dockerfile_build
 test-agent:
  container_name: test-agent-deltachat
  image: test:latest
  build:
   context: .
   dockerfile: Dockerfile_test
  depends_on:
  - build-agent
