version: '3.3'
services:
 build-agent:
  container_name: deltachat
  image: deltachat:latest
  build:
   context: .
   dockerfile: ./deltachat/deltachat-build/Dockerfile
 test-agent:
  container_name: deltachat-test
  image: deltachat-test:latest
  build:
   context: .
   dockerfile: ./deltachat/deltachat-test/Dockerfile
  depends_on:
  - build-agent
