pipeline {
    agent any
  
    stages {
        stage('Build') { 
            steps {
                echo 'Building'
                sh 'git pull origin master'
                nodejs('npm') {
                    sh 'npm install'
                }
            }
        
        post {
        failure {
            echo 'Success'
            emailext attachLog: true,
                body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
                recipientProviders: [developers(), requestor()],
                to: 'maciek.ogorek12@gmail.com',
                subject: "Build failed in Jenkins"
        }
        success {
            echo 'Fail'
            emailext attachLog: true,
                body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
                recipientProviders: [developers(), requestor()],
                to: 'maciek.ogorek12@gmail.com',
                subject: "Successful build in Jenkins"
        }
    }
}
        stage('Test') { 
        when{
                expression {"SUCCESS".equals(currentBuild.currentResult)}
        }
            steps {
                echo 'Testing'
                nodejs('npm') {
                    sh 'npm run test'
                }
                }
            
        
    

    post {
        failure {
            echo 'Success'
            emailext attachLog: true,
                body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
                recipientProviders: [developers(), requestor()],
                to: 'maciek.ogorek12@gmail.com',
                subject: "Build failed in Jenkins"
        }
        success {
            echo 'Fail'
            emailext attachLog: true,
                body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
                recipientProviders: [developers(), requestor()],
                to: 'maciek.ogorek12@gmail.com',
                subject: "Successful build in Jenkins"
        }
    }
}
    stage('Deploy') {
            steps {
                echo 'Deploying..'
		sh 'docker build -t node-chat-app-deploy -f Dockerfile-deploy .'
          }
    
	

	 post {
		success {
		    emailext attachLog: true,
		        body: "${currentBuild.currentResult} in job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
		        recipientProviders: [developers(), requestor()],
		        to: 'maciek.ogorek12@gmail.com',
		        subject: "JENKINS successful deploy"
		}
		failure {
		    emailext attachLog: true,
		        body: "${currentBuild.currentResult} in job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
		        recipientProviders: [developers(), requestor()],
		        to: 'maciek.ogorek12@gmail.com',
		        subject: "JENKINS deploy failed"
		}
	}
    }
    }
}
