pipeline {
    agent any
   
    stages {
        stage('Build'){
            steps {
                sh 'sudo curl -sL https://deb.nodesource.com/setup_14.x | bash -'
                sh 'sudo apt-get install nodejs -y'
                sh 'sudo npm install --global --force yarn'

                sh 'sudo yarn'
                sh 'sudo yarn build'
            }
            post {
                always {
                    echo "Build stage finished";
                }
                success{
                    echo "Build Success";
                }
                failure {
                    echo "Build Failure";
                    mail body: "Please visit jenkins for further information", subject: "Build failed", to: "kkkkkarol@onet.pl";
                }
            }
        }
        stage('Test') {
            when {
              expression {
                currentBuild.result == null || currentBuild.result == 'SUCCESS' 
              }
            }
            steps {
                sh 'yarn test'
                
            }

            post {
                always {
                    echo "Test stage finished";
                }
                success{
                    echo "Test Success";
                }
                failure {
                    echo "Test Failure";
                    mail body: "Please visit jenkins for further information", subject: "Build failed", to: "kkkkkarol@onet.pl";
                }
            }
        }
        stage('DeployTest') {
            when {
              expression {
                currentBuild.result == null || currentBuild.result == 'SUCCESS' 
              }
            }
            steps {
                sh 'yarn test'
            }

            post {
                always {
                    echo "Deploy stage finished";
                }
                success{
                    echo "Deploy Success";
                }
                failure {
                    echo "Deploy Failure";
                    mail body: "Please visit jenkins for further information", subject: "Build failed", to: "kkkkkarol@onet.pl";
                }
            }
        }
    }
}
