apiVersion: apps/v1
kind: Deployment
metadata:
  name: deltachat-deployment
  labels:
    app: deltachat
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deltachat
  template:
    metadata:
      labels:
        app: deltachat
    spec:
      containers:
      - name: deltachat
        image: krzysztofgac/myjenkins-blueocean:lab5
        ports:
        - containerPort: 3000
