version: '3.9'

services:
    jenkins-docker-driver:
        image: docker:dind
        privileged: true
        networks:
            jenkins:
                aliases:
                    - docker
        environment:
            - DOCKER_TLS_CERTDIR=/certs
        volumes:
            - jenkins-docker-certs:/certs/client
            - jenkins-data:/var/jenkins_home
        expose:
            - "2376"
        ports:
            - "2376:2376"

    jenkins:
        image: jenkins:latest
        build:
            context: ./
            dockerfile: jenkins.Dockerfile
        networks:
            - jenkins
        environment:
            - DOCKER_HOST=tcp://docker:2376
            - DOCKER_CERT_PATH=/certs/client
            - DOCKER_TLS_VERIFY=1
        volumes:
            - jenkins-data:/var/jenkins_home
            - jenkins-docker-certs:/certs/client:ro
        ports:
            - "8080:8080"
            - "50000:50000"
        depends_on:
            - jenkins-docker-driver

networks:
    jenkins:

volumes:
    jenkins-data:
    jenkins-docker-certs:
