version: '3.9'

services:
    # has to be named docker, because network alias does not seem to be working
    docker:
        image: docker:dind
        privileged: true
        networks:
            - jenkins
        environment:
            - DOCKER_TLS_CERTDIR=/certs
        volumes:
            - jenkins-docker-certs:/certs/client
            - jenkins-data:/var/jenkins_home
            - docker-data:/var/lib/docker
        expose:
            - "2376"

    jenkins:
        image: jenkins:latest
        build:
            context: ./
            dockerfile: jenkins.Dockerfile
        networks:
            - jenkins
            - ngrok
        environment:
            - DOCKER_HOST=tcp://docker:2376
            - DOCKER_CERT_PATH=/certs/client
            - DOCKER_TLS_VERIFY=1
            - JAVA_OPTS=-Djenkins.security.ApiTokenProperty.adminCanGenerateNewTokens=true
        volumes:
            - jenkins-data:/var/jenkins_home
            - jenkins-docker-certs:/certs/client:ro
        ports:
            - "8080:8080"
            - "50000:50000"
        depends_on:
            - docker

    ngrok:
        image: wernight/ngrok
        ports:
            - "4040:4040"
        networks:
            - ngrok
        depends_on:
            - jenkins
        command: "ngrok http jenkins:8080"

networks:
    jenkins:
    ngrok:

volumes:
    jenkins-data:
    jenkins-docker-certs:
    docker-data:
