version: "3.9"
services:
  build-agent:
    image: build-agent:latest
    build:
      context: .
      dockerfile: Dockerfile_Build
  test-agent:
    image: test-agent:latest
    build:
      context: .
      dockerfile: Dockerfile_Test
    depends_on:
    - build-agent
