apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: komunikator
spec:
  replicas: 4
  selector:
    matchLabels:
      app: komunikator
  template:
    metadata:
      labels:
        app: komunikator
    spec:
      containers:
      - name: komunikator
        image: wsmieja/node-chat-app:deploy
        ports:
        - containerPort: 80

