pipeline{
	agent any
	tools {
	    nodejs "NodeJS"
	}
  stages {
      stage('Build') {
          steps {
              echo 'Building'
              sh 'npm install'
          }
      }
      stage('Test') {
          steps {
              echo 'Testing'
              sh 'npm run test'
          }
      }
  }
	post{

		always{
			echo 'Finished'
		}
		failure{
				echo 'Failure'
		}
		success{
      echo 'Success'
		}
	}
}
