apiVersion: apps/v1
kind: Deployment
metadata:
  name: komunikator-deployment-v2
  labels:
    app: komunikator
spec:
  replicas: 6
  selector:
    matchLabels:
      app: komunikator
  template:
    metadata:
      labels:
        app: komunikator
    spec:
      containers:
      - name: komunikator-deployment-v2
        image: perkele4040/perkelerepo
        ports:
        - containerPort: 80
