pipeline {
    agent any 
    
    tools {nodejs "node"}
    
    stages {
        stage('Build') { 
            steps {
                echo 'Build in progress'
                sh 'npm install'
                
            }
            post {
        	failure {
            		emailext attachLog: true,
                	body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
                	to: 'jakub.straszak99@gmail.com',
                	subject: "Build failed"
        	}
        	success {
            		emailext attachLog: true,
                	body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
                	to: 'jakub.straszak99@gmail.com',
                	subject: "Build success"
        	}
    		}
        }

    
    
    
        stage('Test') { 
            steps {
                echo 'Test in progress'
                sh 'npm run test'
            }
            post {
        	failure {
            		emailext attachLog: true,
                	body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
                	to: 'jakub.straszak99@gmail.com',
                	subject: "Test failed"
        	}
        	success {
            		echo 'Test success'
        	}
    		}
        }
    }
}
