version: '3.3'
services:
 build-agent:
  container_name: deltachat
  image: deltachat:latest
  build:
   context: .
   dockerfile: chat-build
 test-agent:
  container_name: deltachat-test
  image: deltachat-test:latest
  build:
   context: .
   dockerfile: chat-test
  depends_on:
  - build-agent
