apiVersion: apps/v1
kind: Deployment
metadata:
  name: komunikator-deployment
  labels:
    app: chat
spec:
  replicas: 10
  selector:
    matchLabels:
      app: komunikator
  template:
    metadata:
      labels:
        app: komunikator
    spec:
      containers:
      - name: komunikator
<<<<<<< HEAD
        image: kjop118/deploy-chat
=======
        image: kjop118/ubuntu-deploy
>>>>>>> Grupa02
        ports:
        - containerPort: 3000
