version: '3.3'
services:
 build-agent:
  container_name: build-agent-deltachat
  image: build:latest
  build:
   context: .
   dockerfile: Dockerfile
 test-agent:
  container_name: test-agent-deltachat
  image: test:latest
  build:
   context: .
   dockerfile: DockerfileTest
  depends_on:
  - build-agent
