#!/bin/bash
pattern='^(\MS306511)'								
msg="Aborting commmit - message doesn't match pattern!" 

if ! grep -iqE "$pattern" "$1"; then 	
	echo "$msg"							
	exit 1;								
fi
echo "Commit message OK!"