pipeline {
	agent any
	
	tools {
	    nodejs "my-node"
	}
	
	stages {
	
		stage('Build') {
			steps {
				echo 'Building...'
				sh 'npm install'
			}
			post {
				success {
            				echo 'Build finished without failure'
				}
				failure {
					postFailure('Build')
    				}
			}
		}
		
		
		stage('Test') {
			steps {
				echo 'Testing...'
				sh 'npm test'
			}
			post {
				success {
            				echo 'Tests finished without failure'
				}
				failure {
					postFailure('Test')
    				}
			}
		}
		
		stage('Deploy') {
			steps {
				echo 'Deploying...'
				sh 'docker build -t deploy -f Dockerfile-deploy .'
			}
			
			post {
				success {
            				echo 'Deploy finished without failure'
				}
				failure {
					postFailure('Deploy')
    				}
			}
		}
		
	}
}

def postFailure(stageName) {
	echo "${stageName} failed - sending email and aborting"
	emailext attachLog: true,
	body: "Something is wrong with ${stageName} stage - ${env.BUILD_URL}",  
	subject: "Failed Pipeline: ${currentBuild.fullDisplayName}", 
	to: 'ulekk19@gmail.com'
}
