pipeline {

    agent any

    stages{

        stage('Build'){

            steps{
                
                echo 'Building app'
                sh 'cd ../Docker'
                sh 'docker-compose up -d chat-build'
                

            }

        }

        stage('Test'){

            steps{
                
                echo 'Start testing'
                sh 'cd ../Docker'
                sh 'docker-compose up -d chat-test'
                sh 'docker-compose logs > logs.txt'
                

            }
        }
    }
        
    post {
        success {
            emailext attachLog: true, attachmentsPattern: 'logs.txt',
                    body: "Test status: ${currentBuild.currentResult}: Job ${env.JOB_NAME}, More informations in attachment",
                    subject: 'Tests passed',
                    to: 'jopkarolina18@gmail.com'

        }

        failure {
            emailext attachLog: true, attachmentsPattern: 'logs.txt',
                    body: "Test status: ${currentBuild.currentResult}: Job ${env.JOB_NAME}, More informations in attachment",
                    subject: 'Tests failed',
                    to: 'jopkarolina18@gmail.com'
        }
    }
        
    
}
