#!/bin/sh
echo "To jest commit hook, który będzie kiedyś uruchamiał Pipeline po każdym nowym commicie"
curl -X POST -L --user wnowak8:11239c8ef7408923df41121dea1ba429e4 http://localhost:8080/job/LAB_07/build
