pipeline {
    agent any
    stages {
        stage('Build'){
            steps{
		sh 'ls'

            }
	}
	stage('Test'){
	    agent {
                    docker { image 'node:alpine'
                      }
                 }
            steps{
		sh 'docker-compose up'
                sh 'code/wait.sh server:1234 -- echo READY && node code/client.js'
            }
 	}
    }
    post {
    failure {
        mail to: 'zarczynski.adas@gmail.com',
             subject: "Failed Pipeline: ${currentBuild.fullDisplayName}",
             body: "Problem with ${env.BUILD_URL}"
    }
    success {
            echo 'Success'
    }
}
}