pipeline{
	agent any
  stages {
	  stage('Build'){
		  steps{
			  echo 'Building'
			  sh 'git pull origin master'
			  sh 'npm install'
			  sh 'npm --version'
			  sh 'npm run build'
			  script {
			  	build_pom = env.STAGE_NAME
			  }			  
		  }
	}
   
      stage('Test') {
        steps {
        
        	script{
        		build_pom=env.STAGE_NAME
        		if("${currentBuild.currentResult}"=='SUCCESS')
        		{
        			echo 'Testing'
              			sh 'npm run test'
              		}
              		else
              		{
              		echo "Build:${currentBuild.currentResult}"
              		}
          	}
      
  	}
  }
 }
	post{
		failure{
			echo 'Test Failed'
			emailext attachLog: true,
          		body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
			to: 'rafal.widziszewski@gmail.com',
			subject: "Test failed"
		}
		success{
      			echo 'Test Successful'
      			emailext attachLog: true,
        		body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BUILD_NUMBER}",
        		to: 'rafal.widziszewski@gmail.com',
        		subject: "Test success"
			}
		}
	}

