#!/bin/sh

echo "To jest commit hook, który będzie kiedyś uruchamiał Pipeline po każdym nowym commicie"
curl -X POST -L --user malw:11c8896674e9267707249554c7e1d86771 http://localhost:8080/job/lab9/build
