pipeline {
	agent { 
		docker { image 'node:alpine'}
	}
	stages {
		stage('Test') {
			steps {
				sh 'npm test'
			} 
			
		}
		post {
			success{
				mail to: 'pmroz@student.agh.edu.pl', 
				subject: 'The pipeline ${currentBuild.fullDisplayName}tests succeeded'
				body: 'test succeeded'
			}
			failure{
				mail to: 'pmroz@student.agh.edu.pl', 
				subject: 'The pipeline ${currentBuild.fullDisplayName} tests failed'
				body: '${env.BUILD_URL}'
			}
		}
		
	}
}
