buildSucceeded=false
pipeline {
	agent { 
		docker { image 'node:alpine'}
	}
	stages {
		stage('Build') {
			steps {
				sh 'npm install'
				sh 'cd /home/paula/communicator'
				sh 'git checkout master'
				sh 'git pull'
				sh 'docker-compose up -d'
			}
			post {
				success{
					buildSucceeded=true
					mail to: 'pmroz@student.agh.edu.pl', 
					subject: 'The pipeline ${currentBuild.fullDisplayName} 							build succeeded'
					body: 'build succeeded'
				}
				failure{
					mail to: 'pmroz@student.agh.edu.pl', 
					subject: 'The pipeline ${currentBuild.fullDisplayName} build failed'
					body: '${env.BUILD_URL}'
				}
			}
		}
		stage('Test') {
			when{
				buildSucceeded==true
			}
			steps {
				sh 'npm test'
			} 
			post {
				success{
					mail to: 'pmroz@student.agh.edu.pl', 
					subject: 'The pipeline ${currentBuild.fullDisplayName} 								tests succeeded'
					body: 'test succeeded'
				}
				failure{
					mail to: 'pmroz@student.agh.edu.pl', 
					subject: 'The pipeline ${currentBuild.fullDisplayName} tests failed'
					body: '${env.BUILD_URL}'
				}
			}
		}
		
	}
}
