version: '3.3'
services:
 build:
  container_name: nodechat_builder
  image: builder:latest
  build:
   context: .
   dockerfile: Dockerfile_builder
 test:
  container_name: nodechat_tester
  image: tester:latest
  build:
   context: .
   dockerfile: Dockerfile_tester
  depends_on:
  - build
