FROM ubuntu:latest

ENV TZ=Europe/Warsaw
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt-get update && apt-get install git -y && apt-get install npm -y

COPY . Socket.io-Messenger/
WORKDIR Socket.io-Messenger

EXPOSE 3000
CMD ["npm", "install"]
CMD ["npm", "start"]
