pipeline {
	agent any
	tools {nodejs "node"}
	
	stages {
		stage('Test') {
			steps {
				echo 'testing in progress'
				sh 'npm install'
				sh 'npm run test'
			}
		}
	}
	
	post {
		failure {
			emailext attachLog: true,
			body: "${currentBuild.currentResult}: Job ${env.JOB_NAME} build ${env.BILD_NUMBER}",
			to: 'jakub.straszak99@gmail.com',
			subject: "Build Failure"
		}
		
		succes {
			echo 'Build completed'
		}
	}
}
