apiVersion: apps/v1
kind: Deployment
metadata:
        name: komunikator-deployment
        labels:
                app: komunikator
spec:
        replicas: 5
        selector:
                matchLabels:
                        app: komunikator
        template:
                metadata:
                        labels:
                                app: komunikator
                spec:
                        containers:
                                - name: komunikator
                                  image: wiktorwanat/node-chat-app:latest
                                  ports:
                                          -containerPort: 9999

