version: '3.3'
services:
 build-agent:
  container_name: build-agent-deltachat
  image: zad3
  build:
   context: .
   dockerfile: Dockerfile
 test-agent:
  container_name: test-agent-deltachat
  image: zad4
  build:
   context: .
   dockerfile: Dockerfile
  depends_on:
  - build-agent