version: '3.3'
services:
 chat:
  image: chat:latest
  build:
   context: .
   dockerfile: Dockerfile.build
 chat-test:
  image: chat-test:latest
  build:
   context: .
   dockerfile: Dockerfile.test
  depends_on:
   - chat
