version: '3.3'
services:
    build:
        container_name: build
        image: build:latest
        build:
            context: .
            dockerfile: Dockerfile-build
    test:
        container_name: test
            image: test:latest
            build:
                context: .
                dockerfile: Dockerfile-test
            depends_on:
            - build-agent