apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app
  labels:
    app: node
spec:
  replicas: 4
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
      - name: komnikator
        image: b0niu/lab5
        ports:
        - containerPort: 80
