pipeline {
	agent any
	tools {nodejs "node"}

	stages {
		stage('Build') { 
		    steps {
		        echo 'Build'
			checkout scm
	            	sh 'npm install'
			sh 'npm run build'
	    }
		}
		stage('Test') { 
			    	steps {
				echo 'Test'
				
				    sh 'npm run test'
				
		    	}
		}
    	}
	post {
		always {
	    		echo 'Finished'
		}
		success {
	    		echo 'Success'
			emailext attachLog: true, 
		    		body: "Success",
		    		subject: "Pipeline Test Passed",
		    		to: 'dominikabmatuszyk@gmail.com'
		}
		failure {
			echo 'Failure'
		        emailext attachLog: true, 
		    		body: "Error:  ${env.BUILD_URL}",
		    		subject: "Pipeline Test Failed",
		    		to: 'dominikabmatuszyk@gmail.com'
		}
	}
}
